### ISSUE TITLE
[Question] Docs?

### ISSUE THREAD

**Issue by Pk13055** [python-cas/python-cas#38]
Where can I find the documentation on the functionality and how I might proceed to integrate this into a web application?

**Comment by mingchen** [comment]
If you have a Django web application, you should use [django-cas-ng](https://djangocas.dev/?utm-source=python-cas). Otherwise you can reference the implementation of django-cas-ng.
[Checkout this article to see how to integration django-cas-ng step by step](https://djangocas.dev/blog/2020-01-26-django-cas-ng-example-project/?utm-source=python-cas)

**Comment by Pk13055** [comment]
I want a reference to use this directly. Basically, I want to integrate this with the web framework [fastAPI](https://github.com/tiangolo/fastapi)

**Comment by mingchen** [comment]
Then you should follow [API Documentation](https://djangocas.dev/docs/4.0/modules/python_cas.html) to implement [CAS Protocol](https://djangocas.dev/docs/4.0/CAS-Protocol-Specification.html).

**Comment by Pk13055** [comment]
@mingchen Thanks!

**Comment by mingchen** [comment]
I created a sample project to integrate with Flask, you can use as a reference. The integration should be easy.

Checkout this post: [python-cas Flask Example](https://djangocas.dev/blog/2020-02-03-python-cas-flask-example/)

**Comment by Pk13055** [comment]
@mingchen Thank you so much! This is exactly what I needed!
